<<<<<<< HEAD
nome=input("Informe seu nome: ")
cpf=input("Informe seu cpf: ")
rg=input("Informe seu rg: ")
dataNascimento=input("Informe sua data de nascimento: ")
sexo=input("Informe seu sexo: ")
peso=input("Informe seu peso: ")
sangue=input("Informe seu tipo sanguineo: ")
renda=input("Informe sua renda: ")
endereco=input("Informe seu endereço: ")
telefone=input("Informe seu telefone: ")
cidade=input("Informe sua cidade: ")
estado=input("Informe o seu estado: ")
=======
nome=input("Informe seu nome: ")
cpf=input("Informe seu cpf: ")
rg=input("Informe seu rg: ")
dataNascimento=input("Informe sua data de nascimento: ")
sexo=input("Informe seu sexo: ")
peso=input("Informe seu peso: ")
sangue=input("Informe seu tipo sanguineo: ")
renda=input("Informe sua renda: ")
endereco=input("Informe seu endereço: ")
telefone=input("Informe seu telefone: ")
cidade=input("Informe sua cidade: ")
estado=input("Informe o seu estado: ")
>>>>>>> 7984deec003c8b61061ac5b10687a7943a1065b0
print("Nome: %s\n CPF: %s\n RG: %s\n Data de Nascimento: %s\n Sexo: %s\n Peso: %s\n Tipo Sanguíneo: %s\n Renda: %s\n Endereço: %s\n Telefone: %s\n Cidade: %s\n Estado: %s\n "%(nome,cpf,rg,dataNascimento,sexo,peso,sangue,renda,endereco,telefone,cidade,estado))